version: '3'
services:
 mysqldb:
   image: mysql
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
     - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
   ports:
     - '3306:3306'
   volumes:
     - ./data:/var/lib/mysql
 fourlanches-payment-service:
   build:
     context: src
     dockerfile: Dockerfile
   depends_on:
     - mysqldb
   environment:
     - MYSQL_CONNECTION_URL=jdbc:mysql://${DATABASE_HOST}:3306/${DATABASE_BASE}
     - MYSQL_DATABASE_USER=${DATABASE_USERNAME}
     - MYSQL_DATABASE_PASSWORD=${DATABASE_PASSWORD}
   ports:
     - '8080:8080'
 migration:
   container_name: migration
   image: flyway/flyway
   environment:
     - FLYWAY_USER=${DATABASE_USERNAME}
     - FLYWAY_PASSWORD=${DATABASE_PASSWORD}
     - FLYWAY_URL=jdbc:mysql://${DATABASE_HOST}:3306/${DATABASE_BASE}
     - FLYWAY_SCHEMAS=public
     - FLYWAY_GROUP=true
   command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
   volumes:
     - ./src/main/resources/db/migration:/flyway/sql
   depends_on:
     - mysqldb