version: '3'
services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=fourlanches
      - MYSQL_USER=${DATABASE_USERNAME}
    ports:
      - '3306:3306'
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    environment:
      - MYSQL_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/fourlanches
      - MYSQL_DATABASE_USER=${DATABASE_USERNAME}
      - MYSQL_DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '8080:8080'