version: '3'
services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=fourlanches
      - MYSQL_USER=${DATABASE_USERNAME}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
#      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 30
    ports:
      - '3306:3306'
  rabbitmq:
    env_file:
      - .env
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysqldb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - MYSQL_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/fourlanches
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - QUEUE_EXCHANGE=${QUEUE_EXCHANGE}
      - QUEUE_ORDER_STATUS_NAME=${QUEUE_ORDER_STATUS_NAME}
      - QUEUE_IN_PREPARATION_NAME=${QUEUE_IN_PREPARATION_NAME}
      - QUEUE_FINISHED_NAME=${QUEUE_FINISHED_NAME}
      - QUEUE_ORDER_CANCEL_NAME=${QUEUE_ORDER_CANCEL_NAME}
    ports:
      - '8080:8080'